export const INIT = '@@INIT';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_UPDATED = 'CONNECTION_UPDATED';

export const UPDATE_TOKENS = 'UPDATE_TOKENS';
export const TOKENS_LOADED = 'TOKENS_LOADED';

export const WEB3_WAITING = 'WEB3_WAITING';

export const SHOW_CONNECTOR_MODAL = 'SHOW_CONNECTOR_MODAL';

export const FETCH_WALLET = 'FETCH_WALLET';
export const FETCH_VAULT_TRANSACTIONS = 'FETCH_VAULT_TRANSACTIONS';
export const VAULT_POSITIONS_LOADED = 'VAULT_POSITIONS_LOADED';

export const START_LOADING_WALLET = 'START_LOADING_WALLET';
export const WALLET_LOADED = 'WALLET_LOADED';

export const START_LOADING_VAULTS = 'START_LOADING_VAULTS';
export const VAULTS_APY_LOADED = 'VAULTS_APY_LOADED';
export const VAULTS_UPDATED = 'VAULTS_UPDATED';

export const START_LOADING_VAULT_TRANSACTIONS =
	'START_LOADING_VAULT_TRANSACTIONS';

export const START_LOADING_PRICES = 'START_LOADING_PRICES';
export const PRICES_LOADED = 'PRICES_LOADED';
