export const INIT = '@@INIT';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_UPDATED = 'CONNECTION_UPDATED';

export const UPDATE_TOKENS = 'UPDATE_TOKENS';
export const TOKENS_LOADED = 'TOKENS_LOADED';

export const SHOW_CONNECTOR_MODAL = 'SHOW_CONNECTOR_MODAL';

export const START_LOADING_VAULTS = 'START_LOADING_VAULTS';
export const VAULTS_LOADED = 'VAULTS_LOADED';

export const START_LOADING_PRICES = 'START_LOADING_PRICES';
export const PRICES_LOADED = 'PRICES_LOADED';
